
name: Speech-Text-Analysis

on:
  push:
    branches: [main] # Vérifiez si votre branche s'appelle main ou master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://LATSOUCK:$HF_TOKEN@huggingface.co/spaces/LATSOUCK/Speech-Text-Analysis main